import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/global/header";
import Footer from "@/components/global/footer";
import LangProvider from "@/components/global/lang-provider";

const font = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nekaj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <LangProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <div className="max-w-screen-xl mx-auto px-3 md:px-6">
              <Header />
              <main className="my-6">{children}</main>
              <Footer />
            </div>
          </ThemeProvider>
        </LangProvider>
      </body>
    </html>
  );
}
